[package]
name = "ignite-client"
version = "0.1.0"
authors = ["Valentin Kulichenko <valentin.kulichenko@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.5"
num-traits = "0.2.12"
num-derive = "0.3.0"
